spring.application.name=krc-pos-backend

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/springsec_db
spring.datasource.username=postgres
spring.datasource.password=8080
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

#Jwt
jwt.secret=vJ8xVZKoECDSP4lnOlc2X4Rzyeo_3j2fFeFTFXCbg_s
jwt.expiration=900000
